"""empty message

Revision ID: b9f9b5b4e882
Revises: 91732d5540b9
Create Date: 2019-06-14 10:39:42.779170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f9b5b4e882'
down_revision = '91732d5540b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelves'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelve_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_shelve_id_shelves'), 'shelves', ['shelve_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_shelve_id_shelves'), type_='foreignkey')
        batch_op.drop_column('shelve_id')

    op.drop_table('shelves')
    # ### end Alembic commands ###
