"""empty message

Revision ID: d8f2fb9f2472
Revises: b9f9b5b4e882
Create Date: 2022-07-18 21:50:24.181433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f2fb9f2472'
down_revision = 'b9f9b5b4e882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external_path', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_external_path')

    # ### end Alembic commands ###
