language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - name: "xenial"
      python:       # this works for Linux but is ignored on macOS or Windows
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
      dist: xenial

    - name: "trusty"
      python:
        # this works for Linux but is ignored on macOS or Windows
        - "3.0"
        - "3.1"
        - "3.2"
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6"
      dist: trusty

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install: "pip install -e .[test]"

script: pytest

# Push the results back to codecov
after_success:
  - codecov
