language: python

matrix:
  include:
    - name: "xenial 3.4"
      python: "3.4"
      dist: xenial

    - name: "xenial 3.5"
      python: "3.5"
      dist: xenial

    - name: "xenial 3.6"
      python: "3.6"
      dist: xenial

    - name: "xenial 3.7"
      python: "3.7"
      dist: xenial

    - name: "trusty 3.0"
      python: "3.0"
      dist: trusty

    - name: "trusty 3.1"
      python: "3.1"
      dist: trusty

    - name: "trusty 3.2"
      python: "3.2"
      dist: trusty

    - name: "trusty 3.3"
      python: "3.3"
      dist: trusty

    - name: "trusty 3.4"
      python: "3.4"
      dist: trusty

    - name: "trusty 3.5"
      python: "3.5"
      dist: trusty

    - name: "trusty 3.6"
      python: "3.6"
      dist: trusty

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install: "pip install -e .[test]"

script: pytest

# Push the results back to codecov
after_success:
  - codecov
