language: python

matrix:
  include:
    - name: "xenial 2.7"
      python: "2.7"
      dist: xenial

    - name: "xenial 3.4"
      python: "3.4"
      dist: xenial

    - name: "xenial 3.5"
      python: "3.5"
      dist: xenial

    - name: "xenial 3.6"
      python: "3.6"
      dist: xenial

    - name: "xenial 3.7"
      python: "3.7"
      dist: xenial

    - name: "trusty 2.7"
      python: "2.7"
      dist: trusty

    - name: "trusty 3.4"
      python: "3.4"
      dist: trusty

    - name: "trusty 3.5"
      python: "3.5"
      dist: trusty

    - name: "trusty 3.6"
      python: "3.6"
      dist: trusty

    - name: "osx 3.7"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      python: "3.7"

    - name: "osx 3.6"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      python: "3.6"

install: pip install -e .[test]

# https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
script: python3 -m pytest || python -m pytest

# Push the results back to codecov
after_success:
  - codecov
